# Generated by Django 5.1 on 2025-11-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('sabor', models.CharField(max_length=100, unique=True)),
                ('precio', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_elaboracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100, unique=True)),
                ('contacto', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('fecha_registro', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellido', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('fecha_registro', models.DateField()),
                ('productos', models.ManyToManyField(related_name='clientes', to='app_Paleteria.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_Paleteria.proveedor'),
        ),
    ]
