# Generated by Django 5.1 on 2025-11-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Paleteria', '0002_remove_producto_id_proveedor_alter_proveedor_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('sabor', models.CharField(max_length=100, unique=True)),
                ('precio', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_elaboracion', models.CharField(max_length=100)),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_Paleteria.proveedor')),
            ],
        ),
    ]
