# Generated by Django 5.1 on 2025-11-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Paleteria', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellido', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('fecha_registro', models.DateField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='app_Paleteria.producto')),
            ],
        ),
    ]
